export const HOME = '/'
export const ABOUT = '/about'
export const COURSES = '/courses'
export const TESTS_CATEGORIES = '/tests-categories'
export const TESTS_LIST = '/tests-list'
export const QUESTIONS = '/tests-list'
export const COMMON_QUESTIONS = '/common-questions'
export const CONTACT = '/contact'